
version: '2'

services:
  www:
    image: nginx:1.13-alpine
    networks:
      - web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${APP_SITE}"
    volumes:
      - .:/usr/share/nginx:ro

networks:
  web:
    external:
      name: ${DCAPE_NET}
